export const ACTION_TYPES = {
    SET_PLAYING_FILMS: 'SET_PLAYING_FILMS',
    SET_PLAYING_SHOWS: 'SET_PLAYING_SHOWS',
    SET_NEXT_EPISODE_TO_AIR: 'SET_NEXT_EPISODE_TO_AIR',
    GET_MOVIES: 'GET_MOVIES',
    GET_SHOWS:'GET_SHOWS',
    GET_PERSONS:'GET_PERSONS',
    SEARCH_INFO: 'SEARCH_INFO',
};